### ISSUE TITLE
How to install tye: 0.8.0-alpha.21301.1+0fed0b38e730cd07caf0a90287090638c110b77d

### ISSUE THREAD

**Issue by cuno92** [thangchung/practical-clean-ddd#18]
I found that latest Pre-release version of type is **0.7.0.** How can i install 0.8.0 version as Readme instruction

**Comment by thangchung** [comment]
@cuno92 Follows the guidance at https://github.com/dotnet/tye/blob/main/docs/getting_started.md#working-with-ci-builds

```csharp
$ dotnet tool install -g Microsoft.Tye --version "0.8.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
```
